# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/YTX703-common/YTX703L/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),YTX703L)

endif
