# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/YTX703-common/YTX703L/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/bin/sensors.qcom:$(TARGET_COPY_OUT_VENDOR)/bin/sensors.qcom \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/DE.o.msm8952:$(TARGET_COPY_OUT_VENDOR)/firmware/DE.o.msm8952 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/DE.o.msm8976:$(TARGET_COPY_OUT_VENDOR)/firmware/DE.o.msm8976 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225p5_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a330_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a330_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/ice40.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ice40.bin \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/nvm_tlv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv.bin \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/nvm_tlv_1.3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv_1.3.bin \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/nvm_tlv_2.1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv_2.1.bin \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/nvm_tlv_3.0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv_3.0.bin \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/nvm_tlv_3.2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv_3.2.bin \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/rampatch_tlv.img:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv.img \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/rampatch_tlv_1.3.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv_1.3.tlv \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/rampatch_tlv_2.1.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv_2.1.tlv \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/rampatch_tlv_3.0.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv_3.0.tlv \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/rampatch_tlv_3.2.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv_3.2.tlv \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus-v1.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b00 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus-v1.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b01 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus-v1.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b02 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus-v1.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b03 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus-v1.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b04 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus-v1.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.mbn \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus-v1.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.mdt \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mbn \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/widevine.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b04 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/widevine.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b05 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/widevine.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b06 \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/vendor/lib/libmmcamera2_mct.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libmmcamera2_mct.so \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/vendor/lib/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libsensor1.so \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/vendor/lib/soundfx/libswdap.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/soundfx/libswdap.so \
    vendor/lenovo/YTX703-common/YTX703L/proprietary/vendor/vendor/lib64/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib64/libsensor1.so
