# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter zippo heart,$(TARGET_DEVICE)),)

endif
