# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/YTX703-common/YTX703F/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/DE.o.msm8952:vendor/etc/firmware/DE.o.msm8952 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/DE.o.msm8976:vendor/etc/firmware/DE.o.msm8976 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a225_pfp.fw:vendor/etc/firmware/a225_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a225_pm4.fw:vendor/etc/firmware/a225_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a225p5_pm4.fw:vendor/etc/firmware/a225p5_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a300_pfp.fw:vendor/etc/firmware/a300_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a300_pm4.fw:vendor/etc/firmware/a300_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a330_pfp.fw:vendor/etc/firmware/a330_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a330_pm4.fw:vendor/etc/firmware/a330_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a420_pfp.fw:vendor/etc/firmware/a420_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a420_pm4.fw:vendor/etc/firmware/a420_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a530_pfp.fw:vendor/etc/firmware/a530_pfp.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/a530_pm4.fw:vendor/etc/firmware/a530_pm4.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:vendor/etc/firmware/cpp_firmware_v1_10_0.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:vendor/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:vendor/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:vendor/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:vendor/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/cpp_firmware_v1_5_0.fw:vendor/etc/firmware/cpp_firmware_v1_5_0.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:vendor/etc/firmware/cpp_firmware_v1_6_0.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:vendor/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/ice40.bin:vendor/etc/firmware/ice40.bin \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/leia_pfp_470.fw:vendor/etc/firmware/leia_pfp_470.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/leia_pm4_470.fw:vendor/etc/firmware/leia_pm4_470.fw \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/nvm_tlv.bin:vendor/etc/firmware/nvm_tlv.bin \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/nvm_tlv_1.3.bin:vendor/etc/firmware/nvm_tlv_1.3.bin \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/nvm_tlv_2.1.bin:vendor/etc/firmware/nvm_tlv_2.1.bin \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/nvm_tlv_3.0.bin:vendor/etc/firmware/nvm_tlv_3.0.bin \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/nvm_tlv_3.2.bin:vendor/etc/firmware/nvm_tlv_3.2.bin \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/rampatch_tlv.img:vendor/etc/firmware/rampatch_tlv.img \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/rampatch_tlv_1.3.tlv:vendor/etc/firmware/rampatch_tlv_1.3.tlv \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/rampatch_tlv_2.1.tlv:vendor/etc/firmware/rampatch_tlv_2.1.tlv \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/rampatch_tlv_3.0.tlv:vendor/etc/firmware/rampatch_tlv_3.0.tlv \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/rampatch_tlv_3.2.tlv:vendor/etc/firmware/rampatch_tlv_3.2.tlv \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus-v1.b00:vendor/etc/firmware/venus-v1.b00 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus-v1.b01:vendor/etc/firmware/venus-v1.b01 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus-v1.b02:vendor/etc/firmware/venus-v1.b02 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus-v1.b03:vendor/etc/firmware/venus-v1.b03 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus-v1.b04:vendor/etc/firmware/venus-v1.b04 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus-v1.mbn:vendor/etc/firmware/venus-v1.mbn \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus-v1.mdt:vendor/etc/firmware/venus-v1.mdt \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus.b00:vendor/etc/firmware/venus.b00 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus.b01:vendor/etc/firmware/venus.b01 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus.b02:vendor/etc/firmware/venus.b02 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus.b03:vendor/etc/firmware/venus.b03 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus.b04:vendor/etc/firmware/venus.b04 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus.mbn:vendor/etc/firmware/venus.mbn \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/venus.mdt:vendor/etc/firmware/venus.mdt \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/widevine.b00:vendor/etc/firmware/widevine.b00 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/widevine.b01:vendor/etc/firmware/widevine.b01 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/widevine.b02:vendor/etc/firmware/widevine.b02 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/widevine.b03:vendor/etc/firmware/widevine.b03 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/widevine.b04:vendor/etc/firmware/widevine.b04 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/widevine.b05:vendor/etc/firmware/widevine.b05 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/widevine.b06:vendor/etc/firmware/widevine.b06 \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/etc/firmware/widevine.mdt:vendor/etc/firmware/widevine.mdt \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/vendor/lib/libmmcamera2_mct.so:system/vendor/lib/libmmcamera2_mct.so \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/vendor/lib/soundfx/libswdap.so:system/vendor/lib/soundfx/libswdap.so \
    vendor/lenovo/YTX703-common/YTX703F/proprietary/vendor/lib64/libsensor1.so:system/vendor/lib64/libsensor1.so
