# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/YTX703-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter YTX703F YTX703L,$(TARGET_DEVICE)),)

endif
