# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/YTX703-common/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/lenovo/YTX703-common/proprietary
endif
